extern const GeoLayout skybox_3_texture_switch_opt1[];
extern const GeoLayout skybox_3_texture_switch_opt2[];
extern const GeoLayout skybox_3_texture_switch_opt3[];
extern const GeoLayout skybox_3_texture_switch_opt4[];
extern const GeoLayout skybox_3_texture_switch_opt5[];
extern const GeoLayout skybox_3_texture_switch_opt6[];
extern const GeoLayout skybox_3_texture_switch_opt7[];
extern const GeoLayout skybox_3_texture_switch_opt8[];
extern const GeoLayout skybox_3_texture_switch_opt9[];
extern const GeoLayout skybox_geo[];
extern u8 skybox_ocean_rgba16[];
extern u8 skybox_fire_sky_rgba16[];
extern u8 skybox_underwater_city_rgba16[];
extern u8 skybox_clouds_rgba16[];
extern u8 skybox_mountains_rgba16[];
extern u8 skybox_desert_rgba16[];
extern u8 skybox_woods_rgba16[];
extern u8 skybox_dark_world_rgba16[];
extern u8 skybox_sky_rgba16[];
extern u8 skybox_purple_sky_rgba16[];
extern Vtx skybox_dl_mesh_layer_0_vtx_0[1984];
extern Gfx skybox_dl_mesh_layer_0_tri_0[];
extern Gfx mat_skybox_ocean[];
extern Gfx mat_revert_skybox_ocean[];
extern Gfx mat_skybox_fire_sky[];
extern Gfx mat_revert_skybox_fire_sky[];
extern Gfx mat_skybox_underwater_city[];
extern Gfx mat_revert_skybox_underwater_city[];
extern Gfx mat_skybox_clouds[];
extern Gfx mat_revert_skybox_clouds[];
extern Gfx mat_skybox_mountains[];
extern Gfx mat_revert_skybox_mountains[];
extern Gfx mat_skybox_desert[];
extern Gfx mat_revert_skybox_desert[];
extern Gfx mat_skybox_woods[];
extern Gfx mat_revert_skybox_woods[];
extern Gfx mat_skybox_dark_world[];
extern Gfx mat_revert_skybox_dark_world[];
extern Gfx mat_skybox_sky[];
extern Gfx mat_revert_skybox_sky[];
extern Gfx mat_skybox_purple_sky[];
extern Gfx mat_revert_skybox_purple_sky[];
extern Gfx skybox_dl_mesh_layer_0[];
extern Gfx skybox_dl_mesh_layer_0_mat_override_fire_sky_0[];
extern Gfx skybox_dl_mesh_layer_0_mat_override_underwater_city_1[];
extern Gfx skybox_dl_mesh_layer_0_mat_override_clouds_2[];
extern Gfx skybox_dl_mesh_layer_0_mat_override_mountains_3[];
extern Gfx skybox_dl_mesh_layer_0_mat_override_desert_4[];
extern Gfx skybox_dl_mesh_layer_0_mat_override_woods_5[];
extern Gfx skybox_dl_mesh_layer_0_mat_override_dark_world_6[];
extern Gfx skybox_dl_mesh_layer_0_mat_override_sky_7[];
extern Gfx skybox_dl_mesh_layer_0_mat_override_purple_sky_8[];
