extern const GeoLayout skybox_skybox_obj__invisible_[];
extern const GeoLayout skybox_visibility_switch_opt2_skybox_texture_switch_opt1[];
extern const GeoLayout skybox_visibility_switch_opt2_skybox_texture_switch_opt2[];
extern const GeoLayout skybox_visibility_switch_opt2_skybox_texture_switch_opt3[];
extern const GeoLayout skybox_visibility_switch_opt2_skybox_texture_switch_opt4[];
extern const GeoLayout skybox_visibility_switch_opt2_skybox_texture_switch_opt5[];
extern const GeoLayout skybox_visibility_switch_opt2_skybox_texture_switch_opt6[];
extern const GeoLayout skybox_visibility_switch_opt2_skybox_texture_switch_opt7[];
extern const GeoLayout skybox_visibility_switch_opt2_skybox_texture_switch_opt8[];
extern const GeoLayout skybox_visibility_switch_opt2_skybox_texture_switch_opt9[];
extern const GeoLayout skybox_visibility_switch_opt2_skybox_texture_switch_opt10[];
extern const GeoLayout skybox_skybox_obj__textured_[];
extern const GeoLayout skybox_geo[];
extern u8 skybox_clouds_rgba16[];
extern u8 skybox_ocean_rgba16[];
extern u8 skybox_fiery_sky_rgba16[];
extern u8 skybox_underwater_city_rgba16[];
extern u8 skybox_icy_mountains_rgba16[];
extern u8 skybox_desert_rgba16[];
extern u8 skybox_dark_woods_rgba16[];
extern u8 skybox_dark_world_rgba16[];
extern u8 skybox_sky_rgba16[];
extern u8 skybox_purple_sky_rgba16[];
extern Vtx skybox_switch_option_textured_skybox_dl_mesh_layer_1_vtx_0[1984];
extern Gfx skybox_switch_option_textured_skybox_dl_mesh_layer_1_tri_0[];
extern Gfx mat_skybox_clouds[];
extern Gfx mat_skybox_ocean[];
extern Gfx mat_skybox_fiery_sky[];
extern Gfx mat_skybox_underwater_city[];
extern Gfx mat_skybox_icy_mountains[];
extern Gfx mat_skybox_desert[];
extern Gfx mat_skybox_dark_woods[];
extern Gfx mat_skybox_dark_world[];
extern Gfx mat_skybox_sky[];
extern Gfx mat_skybox_purple_sky[];
extern Gfx skybox_switch_option_textured_skybox_dl_mesh_layer_1[];
extern Gfx skybox_switch_option_textured_skybox_dl_mesh_layer_1_mat_override_ocean_0[];
extern Gfx skybox_switch_option_textured_skybox_dl_mesh_layer_1_mat_override_fiery_sky_1[];
extern Gfx skybox_switch_option_textured_skybox_dl_mesh_layer_1_mat_override_underwater_city_2[];
extern Gfx skybox_switch_option_textured_skybox_dl_mesh_layer_1_mat_override_clouds_3[];
extern Gfx skybox_switch_option_textured_skybox_dl_mesh_layer_1_mat_override_icy_mountains_4[];
extern Gfx skybox_switch_option_textured_skybox_dl_mesh_layer_1_mat_override_desert_5[];
extern Gfx skybox_switch_option_textured_skybox_dl_mesh_layer_1_mat_override_dark_woods_6[];
extern Gfx skybox_switch_option_textured_skybox_dl_mesh_layer_1_mat_override_dark_world_7[];
extern Gfx skybox_switch_option_textured_skybox_dl_mesh_layer_1_mat_override_sky_8[];
extern Gfx skybox_switch_option_textured_skybox_dl_mesh_layer_1_mat_override_purple_sky_9[];
